#ifndef     ACH2_SIGNALS_H
#define     ACH2_SIGNALS_H

enum
{
    KM_STURVAL = 0,
    KM_REVERS = 1,

    BUTTON_AVARIA_GTR_1 = 19,
    BUTTON_AVARIA_GTR_2 = 20,
    BUTTON_DISEL_START = 21,
    BUTTON_DISEL_STOP_1 = 22,
    BUTTON_DISEL_STOP_2 = 23,
    BUTTON_DISEL_STOP_AVARIA = 24,
    BUTTON_DIST_SIGNAL = 25,
    BUTTON_FUEL_PUMP = 26,
    BUTTON_GDP_RAZBLOKIROVKA = 27,
    BUTTON_MASHINNOE_SIGNAL = 28,
    BUTTON_PESOK = 29,
    BUTTON_POEZD_STOP_EXT = 30,
    BUTTON_PROVERKA_ALSN = 31,
    BUTTON_SVISTOK = 32,
    BUTTON_TIFON = 33,
    BUTTON_WHITE = 34,

    SIGLIGHT_DOOR = 35,
    SIGLIGHT_DOOR_1 = 36,

    SIGLIGHT_EPT_O = 37,
    SIGLIGHT_EPT_O_1 = 38,
    SIGLIGHT_EPT_P = 39,
    SIGLIGHT_EPT_P_1 = 40,
    SIGLIGHT_EPT_T = 41,
    SIGLIGHT_EPT_T_1 = 42,


    LS_G = 57,
    LS_Y = 58,
    LS_YR = 59,
    LS_R = 60,
    LS_W = 61,


    KRAN395_RUK = 68,
    KRAN254_POD = 69,
    KRAN254_RUK = 193,

    KLUCH_EPK = 71,
    RB1 = 72,

    KARDAN_1 = 198,
    KRADAN_2 = 199,

};

#endif // ACH2_SIGNALS_H
